---
version: "3.7"

services:
  traefik:
    image: traefik:v2.7@sha256:433f851c0abcaa5999301c46d7129a96a6df95a52d09f16847b00ce5f7c1b6ae
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}"
      # letsencrypt configuration
      - "--certificatesResolvers.http.acme.email=${TRAEFIK_ACME_MAIL:-example@example.org}"
      - "--certificatesResolvers.http.acme.storage=/certs/acme.json"
      - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
      # enable dashboard
      - "--api.dashboard=true"
      # define entrypoints
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.http.redirections.entryPoint.to=https"
      - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.https.address=:443"
      # docker provider (get configuration from container labels)
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/certs"
    labels:
      - "traefik.enable=${TRAEFIK_DASHBOARD:-false}"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USERS:-admin:$apr1$4vqie50r$YQAmQdtmz5n9rEALhxJ4l.}" # defaults to admin:admin
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN:-traefik.owncloud.test}`)"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.tls.certresolver=http"
      - "traefik.http.routers.traefik.service=api@internal"
    logging:
      driver: "local"
    restart: always

  grafana:
    image: grafana/grafana:8.5.3@sha256:ecc1b80b8ca27743e48033c6d4c9d9f658b0837f9bea7dc5afeec0f857357267
    volumes:
      - grafana:/var/lib/grafana
      - ./config/grafana/dashboards/:/etc/grafana/dashboards/
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN:-grafana.owncloud.test}
      - GF_SERVER_ROOT_URL=https://${GRAFANA_DOMAIN:-grafana.owncloud.test}
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-github-datasource,grafana-clock-panel
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/home.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN:-grafana.owncloud.test}`)"
      - "traefik.http.routers.grafana.tls.certresolver=http"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    logging:
      driver: "local"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4@sha256:b3fed35f7a43a3e16aa037bf9c8cb8139d1eec879ab5616f3c20746484de4010
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2G -Xmx2G
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./config/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    logging:
      driver: "local"
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.4@sha256:ddd263a6fa663e514fcfa5b0eae6065dbfcf7c3e62fc646621899ef3b47f7870
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "127.0.0.1:5601:5601"
    labels:
      - "traefik.enable=${KIBANA_EXPOSED:-false}"
      - "traefik.http.routers.kibana.entrypoints=https"
      - "traefik.http.routers.kibana.rule=Host(`${KIBANA_DOMAIN:-kibana.owncloud.test}`)"
      - "traefik.http.routers.kibana.tls.certresolver=http"
      - "traefik.http.routers.kibana.service=kibana"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"
      - "traefik.http.middlewares.kibana-auth.basicauth.users=${KIBANA_BASIC_AUTH_USERS:-admin:$apr1$4vqie50r$YQAmQdtmz5n9rEALhxJ4l.}" # defaults to admin:admin
      - "traefik.http.routers.kibana.middlewares=kibana-auth"
    logging:
      driver: "local"
    restart: always

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.34.1@sha256:04e19a78cacb3231f1b062802a04071a08af7efb2a6dfba5cde0726688b01a3d
    command: |
      --span-storage.type=elasticsearch
      --es.server-urls=http://elasticsearch:9200
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger-collector.entrypoints=https"
      - "traefik.http.routers.jaeger-collector.rule=Host(`${JAEGER_COLLECTOR_DOMAIN:-jaeger-collector.owncloud.test}`)"
      - "traefik.http.routers.jaeger-collector.tls.certresolver=http"
      - "traefik.http.routers.jaeger-collector.service=jaeger-collector"
      - "traefik.http.services.jaeger-collector.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.jaeger-collector.loadbalancer.server.port=14250"
    logging:
      driver: "local"
    restart: always

  jaeger-query:
    image: jaegertracing/jaeger-query:1.34.1@sha256:c38ea8ba1c1d747bdaaa70fb8c09efab2b1e7304a6f63f96d118536488248f8b
    command: |
      --span-storage.type=elasticsearch
      --es.server-urls=http://elasticsearch:9200
      --es.sniffer=false
    labels:

      - "traefik.enable=true"
      - "traefik.http.routers.jaeger-query.entrypoints=https"
      - "traefik.http.routers.jaeger-query.rule=Host(`${JAEGER_QUERY_DOMAIN:-jaeger.owncloud.test}`)"
      - "traefik.http.routers.jaeger-query.tls.certresolver=http"
      - "traefik.http.routers.jaeger-query.service=jaeger-query"
      - "traefik.http.services.jaeger-query.loadbalancer.server.port=16686"
      # you can protect your jaeger query instance with basic auth
      #- "traefik.http.middlewares.jaeger-query-auth.basicauth.users=${JAEGER_QUERY_BASIC_AUTH_USERS:-admin:$apr1$4vqie50r$YQAmQdtmz5n9rEALhxJ4l.}" # defaults to admin:admin
      #- "traefik.http.routers.jaeger-query.middlewares=jaeger-query-auth"
    logging:
      driver: "local"
    restart: always

  prometheus:
    image: prom/prometheus:v2.36.0@sha256:18dfa7c0cabaedbef241ca7cecf2ad56c5a86b10c4f583088f30c37bcef312f4
    command:
      - "--web.external-url=https://${PROMETHEUS_DOMAIN:-prometheus.owncloud.test}"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./config/prometheus/scrape_targets:/etc/prometheus/scrape_targets:ro
      - ./config/prometheus/config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    labels:

      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=https"
      - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_DOMAIN:-prometheus.owncloud.test}`)"
      - "traefik.http.routers.prometheus.tls.certresolver=http"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      # you can protect your prometheus instance with basic auth
      #- "traefik.http.middlewares.prometheus-auth.basicauth.users=${PROMETHEUS_BASIC_AUTH_USERS:-admin:$apr1$4vqie50r$YQAmQdtmz5n9rEALhxJ4l.}" # defaults to admin:admin
      #- "traefik.http.routers.prometheus.middlewares=prometheus-auth"
    logging:
      driver: "local"
    restart: always

  telegraf:
    image: telegraf:1.22.4@sha256:3391493c0294260077573b4c9a70042fb67f9819864b089550d563340590a141
    user: telegraf:${HOST_DOCKER_GROUP_ID} # host docker group id, so that telegraf has access to the docker socket
    command: | # only use config directory, but therefore we need to give a empty config file
      --config-directory /etc/telegraf/telegraf.d/
      --config /dev/null
    volumes:
      - ./config/telegraf:/etc/telegraf/telegraf.d:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs:ro
    environment:
      HOSTNAME: ${TELEMETRY_SERVE_DOMAIN:-telemetry.infra.owncloud.test}
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
    logging:
      driver: "local"
    restart: always

volumes:
  certs:
  elasticsearch-data:
  prometheus-data:
  grafana:
