network :
    host : 0.0.0.0

cluster.name: opentrace

discovery.type: single-node
discovery.zen.ping.unicast.hosts: ["0.0.0.0"]
discovery.zen.minimum_master_nodes: 1

indices.fielddata.cache.size: 40%

xpack.security.enabled: false
