global:
  scrape_interval: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "self_monitoring"
    static_configs:
      - targets: [
        "telegraf:9273",
        ]
  - job_name: "test_server"
    static_configs:
      - targets: [
        "telemetry.owncloud.test",
        "172.17.0.1:9273"
        ]
