global:
  scrape_interval: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "self_monitoring"
    static_configs:
      - labels:
          service: infra
        targets:
          - "telegraf:9273"

  - job_name: "oCIS"
    file_sd_configs:
      - files:
          - /etc/prometheus/scrape_targets/ocis.yml

  - job_name: "infra"
    file_sd_configs:
      - files:
          - /etc/prometheus/scrape_targets/infra.yml
