{
 "title": "Basic Docker Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(system_uptime, host)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(docker_container_cpu_usage_total{host=\"$host\"}, com_docker_compose_service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(docker_container_cpu_usage_percent{host=~\"$host\",com_docker_compose_service=~\"$service\"}) by (host, com_docker_compose_service, com_docker_compose_container_number)",
     "legendFormat": "{{com_docker_compose_service}} #{{com_docker_compose_container_number}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(docker_container_mem_usage_percent{host=~\"$host\",com_docker_compose_service=~\"$service\"}) by (host, com_docker_compose_service, com_docker_compose_container_number)",
     "legendFormat": "{{com_docker_compose_service}} #{{com_docker_compose_container_number}}"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(docker_container_net_rx_bytes{host=~\"$host\",com_docker_compose_service=~\"$service\"}) by (host, com_docker_compose_service, com_docker_compose_container_number)",
     "legendFormat": "{{com_docker_compose_service}} #{{com_docker_compose_container_number}}"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(docker_container_net_tx_bytes{host=~\"$host\",com_docker_compose_service=~\"$service\"}) by (host, com_docker_compose_service, com_docker_compose_container_number)",
     "legendFormat": "{{com_docker_compose_service}} #{{com_docker_compose_container_number}}"
    }
   ]
  }
 ]
}